# Generated by Django 5.2 on 2025-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidePoint',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fromCity', models.CharField(max_length=1000)),
                ('toCity', models.CharField(max_length=1000)),
                ('datePoint', models.CharField(max_length=1000)),
                ('contactPoint', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('driverId', models.CharField(max_length=1000)),
            ],
        ),
    ]
