# Generated by Django 5.2 on 2025-04-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ridepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepoint',
            name='applyOn',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
