# Generated by Django 5.2 on 2025-04-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ridepoint_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPoolRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rideId', models.CharField(max_length=1000)),
                ('userId', models.CharField(max_length=1000)),
            ],
        ),
    ]
