# Generated by Django 5.2 on 2025-04-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carpoolrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepoint',
            name='nextUser',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
