# Generated by Django 5.2 on 2025-04-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ridepoint_nextuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStrap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rideId', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='CarPoolRequest',
        ),
        migrations.RemoveField(
            model_name='ridepoint',
            name='nextUser',
        ),
    ]
