# Generated by Django 5.2 on 2025-04-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_paymentstrap_delete_carpoolrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointRide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rider1', models.CharField(max_length=1000)),
                ('rider2', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('whenJoined', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentStrap',
        ),
        migrations.AddField(
            model_name='ridepoint',
            name='payment',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
