# Generated by Django 5.2 on 2025-05-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_jointride_delete_paymentstrap_ridepoint_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jointride',
            old_name='rider1',
            new_name='rideId',
        ),
        migrations.RenameField(
            model_name='jointride',
            old_name='rider2',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='jointride',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jointride',
            name='whenJoined',
        ),
    ]
