# Generated by Django 5.2.1 on 2025-05-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_rider1_jointride_rideid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedRide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rideId', models.CharField(max_length=1000)),
                ('driverId', models.CharField(max_length=1000)),
                ('rejectedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('rideId', 'driverId')},
            },
        ),
    ]
