# Generated by Django 5.2.1 on 2025-05-16 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rejectedride'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=1000)),
                ('destination', models.CharField(max_length=1000)),
                ('distance', models.FloatField()),
                ('fare', models.FloatField()),
                ('transaction_hash', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ridepoint')),
            ],
        ),
    ]
