# Generated by Django 5.2.1 on 2025-05-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepoint',
            name='distance',
            field=models.FloatField(default=50),
        ),
    ]
