# Generated by Django 5.2.1 on 2025-05-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_paymenthistory_distance_paymenthistory_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepoint',
            name='driver_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
