# Generated by Django 5.2.1 on 2025-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ridepoint_driver_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
