# Generated by Django 5.2.1 on 2025-05-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ridepoint_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridepoint',
            name='distance',
            field=models.FloatField(null=True),
        ),
    ]
