# Generated by Django 5.2.1 on 2025-05-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_ridepoint_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceCalculation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ridepoint')),
            ],
        ),
    ]
