# Generated by Django 5.2.1 on 2025-05-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_distancecalculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridepoint',
            name='distance',
        ),
        migrations.CreateModel(
            name='RideDistance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('fare', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_distance', to='app.ridepoint')),
            ],
        ),
    ]
