# Generated by Django 5.2.1 on 2025-06-04 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_emergency_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='jointride',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jointride',
            name='payment_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jointride',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jointride',
            name='walletAddress',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ridepoint',
            name='base_fare',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ridepoint',
            name='current_fare',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ridepoint',
            name='is_carpool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ridepoint',
            name='passenger_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_carpool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='passenger_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jointride',
            name='rideId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jointride',
            name='userid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='applyOn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='contactPoint',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='datePoint',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='driverId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='fromCity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='payment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='toCity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='userid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fare',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
