# Generated by Django 5.2.1 on 2025-06-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_transaction_updated_at_jointride_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepoint',
            name='journey_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ridepoint',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='jointride',
            name='walletAddress',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='base_fare',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='current_fare',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ridepoint',
            name='driverId',
            field=models.CharField(default='', max_length=100),
        ),
    ]
