# Generated by Django 5.2.1 on 2025-06-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_ridepoint_journey_time_ridepoint_phone_number_and_more'),
    ]

    operations = [
    ]
