# Generated by Django 5.2.1 on 2025-06-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20250605_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointride',
            name='walletAddress',
        ),
        migrations.AddField(
            model_name='jointride',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jointride',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
