# Generated by Django 5.2.1 on 2025-06-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_jointride_walletaddress_jointride_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepoint',
            name='women_only',
            field=models.BooleanField(default=False),
        ),
    ]
